### ISSUE TITLE
[Feature]: IMPROVE SEO SCORE BY ADDING IMPORTANT META ELEMENTS 🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ShwetKhatri2001/AR-Webstore#85]
### Description

- I want to add important Meta elements because in HTML they play a crucial role in providing information about the webpage to browsers and search engines.
- Meta elements in HTML serve various purposes, including defining document encoding, improving search engine visibility, enhancing social media sharing, optimizing for mobile devices, and influencing browser behavior. 
- Utilizing appropriate meta elements can significantly impact how webpages are perceived, indexed, and shared on the internet.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Please assign this issue to me @ShwetKhatri2001.

**Comment by ShwetKhatri2001** [comment]
Hi @0xabdulkhalid! There is already issue #84  present covering these points. 
Tell me what kind of changes you will make, I'd like to know whether it's different from that issue or not.

**Comment by 0xabdulkhalid** [comment]
Hey there @ShwetKhatri2001, he is only mentioning meta tags for description and keywords.

But the `description` is already present, and `keyword` is isn't enough.

There are crucial other Meta elements like "og:title," "og:description," and "og:image" are part of Open Graph protocol and are used for social media sharing. When a webpage is shared on platforms like Facebook or Twitter, these meta elements provide specific information such as the title, description, and image to be displayed, enhancing the visual appeal and context of the shared content

I want to add every important meta elements to this site to boost site's vital score and performance.

**Comment by ShwetKhatri2001** [comment]
Okay, Go ahead and implement this. You're assigned.
